project:
  type: book
  output-dir: docs

toc: true
number-sections: true
toc-depth: 2
number-depth: 4
bibliography: book.bib
csl: ims.csl

execute:
  freeze: auto


jupyter: stats

knitr:
  opts_chunk:
    # comment: "#>"
    collapse: true
 
    
# custom-numbered-blocks:
#   classes:
#     # Theorem:
#     #   colors: [948bde, 584eab]
#     #   boxstyle: foldbox.simple
#     #   collapse: false 
#     Proof:
#       numbered: false 
# filters:
#   - custom-numbered-blocks
 
format:
  bookup-html:
        toc: true
        toc-depth: 3
  # html:
  #   theme: united 
    # page-layout: article
    # include-before-body: 
    # - file: contents/math.qmd
crossref:
  appendix-title: "Appendix "
  appendix-delim: ":"
book:
  title: "Stats"
  subtitle: "Notes"
  description: "Homepage {{< var info.date >}}."
  author: "Xinli Xiao"
  date: last-modified
  chapters: 
    - index.qmd
    - part: contents/0/rv.qmd
      chapters:
          - contents/0/prob.qmd 
          - contents/0/basics.qmd
          - contents/0/inferences.qmd
          - contents/0/statsmodels.qmd
    - part: contents/1/notations.qmd
      chapters: 
        - contents/1/dist/binom.qmd
        - contents/1/dist/beta.qmd
        - contents/1/dist/chisquare.qmd
        - contents/1/dist/poisson.qmd
        - contents/1/dist/gamma.qmd
    #     - contents/1/dist/exp.qmd
        - contents/1/dist/normal.qmd
    - part: "SLR"
      chapters:
        - contents/2/slr.qmd
        - contents/2/project1.qmd
        - contents/2/mlr.qmd
        - contents/2/misc.qmd
    - part: "misc"
      chapters: 
        - contents/3/simulation.qmd
        - contents/3/resample.qmd
        - contents/3/jackknife.qmd
  appendices:
    - contents/app/specialfunctions.qmd
    - contents/app/linearalgebra.qmd 
    - contents/app/multi.qmd 
  sidebar:
    # background: "#D9E3E4"
    border: true
    search: true
    collapse-level: 1
    pinned: true
    style: "docked"
    # style: "floating"
    downloads: [pdf]
    reader-mode: true
    align: center
    # tools:
    #   - icon: github
    #     text: Source Code
    #     href: https://github.com/xiaoxl/stats
  # navbar:
  #   subtitle: "2023 Fall"
  #   pinned: true
  page-navigation: false
  bread-crumbs: false





  

